[tool.poetry]
name = "notefly"
version = "0.1.0"
description = ""
authors = ["Steven Almeroth <fedor@primesite.dev>"]
readme = "README.md"
packages = [{include = "notefly", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
quart = "^0.18.4"
quart-cors = "^0.6.0"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.21.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chat = "chat:run"
broker = "notefly:broker"
client = "notefly:client"

[tool.pytest.ini_options]
asyncio_mode = "auto"
